#pragma once
#ifndef VELD_FIRST_ACTIVATION_CUSTODY_SPK_HEX
#error "supply a freshly generated Bitcoin Core regtest wallet custody script"
#endif
#define VELD_MAINNET_POW 1
#define VELD_TEST_CHAIN_BUILD 1
#define VELD_REGTEST_FIXED_DIFF 1
#define VELD_BTCVELD_REGTEST 1
#ifndef VELD_FIRST_ACTIVATION_AUTHORITY_ADDRESS
#error "Supply the freshly generated disposable Veld launch authority"
#endif
#define VELD_L3_DISPOSABLE_BTCVELD_AUTHORITY_ADDRESS VELD_FIRST_ACTIVATION_AUTHORITY_ADDRESS
#define VELD_L3_DISPOSABLE_BTCVELD_CUSTODY_SPK_HEX VELD_FIRST_ACTIVATION_CUSTODY_SPK_HEX
#define VELD_TEST_HOOKS 1
#define VELD_TEST_GOV_GATE 1
#define VELD_TEST_STAKE_OUTPOINT_BACKING 1
#define VELD_TEST_BTC_CUSTODY_LINEAGE 1
#define VELD_TEST_BTC_REDEEM_BINDING 1
#define VELD_TEST_BTC_RELAY_FRESHNESS 1
#define VELD_TEST_BTC_OBSERVATION_FINALITY 1
#define VELD_TEST_AMM_MARKET_SEED 1
#ifndef VELD_FIRST_ACTIVATION_MIGRATION_HEIGHT
#define VELD_FIRST_ACTIVATION_MIGRATION_HEIGHT 3360
#endif
#define VELD_SECURITY_STATE_MIGRATION_TEST_HEIGHT VELD_FIRST_ACTIVATION_MIGRATION_HEIGHT
#define VELD_LOCAL_TEST_NETWORK 1
