// Generated by scripts/generate-pool-overview-ui.py.
#pragma once
inline constexpr const char* VELD_POOL_OVERVIEW_JS =
    R"VLDPOOLUI(/* Public pool statistics. No account credentials or wallet access. */
(function () {
  'use strict';
  var page = document.querySelector('.pool-page');
  if (!page || document.getElementById('pool-overview')) return;
  var overview = document.createElement('section');
  overview.id = 'pool-overview';
  overview.setAttribute('aria-label', 'Pool performance and earnings');
  overview.innerHTML = '<div class="pool-overview-grid">' +
    '<article class="tile"><div class="l">Pool hashrate</div><div class="v" id="pool-rate">—</div><small id="pool-rate-note">Measured from verified work</small></article>' +
    '<article class="tile"><div class="l">Blocks won</div><div class="v" id="pool-blocks">—</div><small>Canonical pool blocks</small></article>' +
    '<article class="tile"><div class="l">Mining rewards earned</div><div class="v" id="pool-earned">—</div><small>Actual miner outputs · VELD</small></article>' +
    '<article class="tile"><div class="l">Paid to miners</div><div class="v" id="pool-paid">—</div><small id="pool-paid-note">Confirmed payments · VELD</small></article></div>' +
    '<p class="pool-note" id="pool-stats-updated" role="status">Loading pool statistics…</p>';
  var intro = page.querySelector('.pool-intro') || page.querySelector('h2');
  intro.insertAdjacentElement('afterend', overview);
  var recent = document.createElement('section');
  recent.className = 'pool-recent';
  recent.innerHTML = '<h3>Recent pool blocks</h3><p class="pool-note">Rewards mature for at least 120 confirmations and must be spendable before payment.</p>' +
    '<div class="pool-block-table"><table><thead><tr><th>Block</th><th>Miner reward</th><th>Confirmations</th><th>Status</th></tr></thead><tbody id="pool-block-rows"></tbody></table></div>' +
    '<div class="pool-extra-rewards"><p>Lottery winnings <strong id="pool-lottery-earned">—</strong></p><p>Staking distributions <strong id="pool-stake-earned">—</strong></p></div>' +
    '<p class="pool-note">Earned rewards include funds still maturing or waiting for a payment batch. They are different from confirmed payments.</p>';
  var setup = Array.from(page.querySelectorAll('h3')).find(function (h) { return h.textContent === 'Start pool mining'; });
  if (setup) page.insertBefore(recent, setup); else page.appendChild(recent);
  function put(id, text) { document.getElementById(id).textContent = text; }
  function object(v) { if (!v || typeof v !== 'object' || Array.isArray(v)) throw Error('Object required'); return v; }
  function uint(v) { if (typeof v !== 'string' || !/^(0|[1-9][0-9]{0,19})$/.test(v)) throw Error('Invalid integer'); return BigInt(v); }
  function money(v, places) { var n = uint(v), fraction = (n % 100000000n).toString().padStart(8, '0'); return (n / 100000000n).toLocaleString() + '.' + (places === 2 ? fraction.slice(0, 2) : fraction.replace(/0+$/, '').padEnd(2, '0')); }
  function count(v) { return uint(v).toLocaleString(); }
  function rate(v) { var n = uint(v), scale = n >= 1000000n ? 1000000n : n >= 1000n ? 1000n : 1n; return (n / scale).toLocaleString() + (scale > 1n ? '.' + (n % scale * 100n / scale).toString().padStart(2, '0') : '') + (scale === 1000000n ? ' MH/s' : scale === 1000n ? ' kH/s' : ' H/s'); }
  function validate(payload) {
    object(payload); var result = object(payload.result);
    if (payload.ok !== true || result.chain !== '7be77ab9e820bd9ffb60b269b45ced48288056e5839a1135fafc2f8557000a88') throw Error('Wrong network');
    var o = object(result.overview), w = object(o.work); object(o.payments); object(o.reward_totals);
    if (o.version !== 1 || w.method !== 'verified-expected-work' || w.bucket_seconds !== '10' || uint(w.window_seconds) > 600n || typeof w.warming_up !== 'boolean') throw Error('Unknown statistics');
    if (w.hashrate_hs !== null) uint(w.hashrate_hs);
    uint(w.sample_shares); uint(o.blocks_won); uint(o.payments.paid_units); uint(o.payments.confirmed_transactions);
    ['mining', 'comine_payout', 'staking_distribution'].forEach(function (k) { uint(o.reward_totals[k]); });
    if (!Array.isArray(o.recent_blocks) || o.recent_blocks.length > 12) throw Error('Too many blocks');
    o.recent_blocks.forEach(function (b) { object(b); uint(b.height); uint(b.amount_units); uint(b.confirmations); if (!/^[0-9a-f]{64}$/.test(b.hash) || !['pending', 'available', 'orphaned'].includes(b.state)) throw Error('Invalid block'); });
    if (typeof result.co_mining_enabled !== 'boolean') throw Error('Invalid co-mining state');
    return {overview: o, coMining: result.co_mining_enabled};
  }
  function row(text, label) { var td = document.createElement('td'); td.textContent = text; td.dataset.label = label; return td; }
  function empty(text) { var tr = document.createElement('tr'), td = row(text, ''); td.colSpan = 4; tr.appendChild(td); document.getElementById('pool-block-rows').replaceChildren(tr); }
  function render(data) {
    var o = data.overview;
    put('pool-rate', o.work.hashrate_hs === null ? 'Measuring…' : rate(o.work.hashrate_hs));
    put('pool-rate-note', (o.work.warming_up ? 'Warming up · ' : '') + count(o.work.sample_shares) + ' verified shares · ' + o.work.window_seconds + 's window');
    put('pool-blocks', count(o.blocks_won)); put('pool-earned', money(o.reward_totals.mining, 2)); put('pool-paid', money(o.payments.paid_units, 2));
    document.getElementById('pool-earned').title = money(o.reward_totals.mining) + ' VELD';
    document.getElementById('pool-paid').title = money(o.payments.paid_units) + ' VELD';
    var lotteryNote = document.getElementById('pool-public-comining-note');
    if (lotteryNote) lotteryNote.textContent = data.coMining ? 'Co-mining is enabled. Only confirmed pool winnings create earnings.' : 'The pool needs 1,000 VELD staked to qualify. Lottery winnings and staking distributions are shared with contributors.';
    put('pool-paid-note', count(o.payments.confirmed_transactions) + ' confirmed payments · VELD');
    put('pool-lottery-earned', money(o.reward_totals.comine_payout) + ' VELD'); put('pool-stake-earned', money(o.reward_totals.staking_distribution) + ' VELD');
    var rows = document.createDocumentFragment();
    o.recent_blocks.forEach(function (b) {
      var tr = document.createElement('tr'), block = row('', 'Block'), link = document.createElement('a');
      link.href = '/block/' + b.hash; link.textContent = '#' + count(b.height); block.appendChild(link); tr.appendChild(block);
      tr.appendChild(row(money(b.amount_units) + ' VELD', 'Miner reward')); tr.appendChild(row(count(b.confirmations), 'Confirmations'));
      var status = row({pending: 'Maturing', available: 'Mature', orphaned: 'Orphaned'}[b.state], 'Status'); status.className = 'pool-block-state ' + b.state; tr.appendChild(status); rows.appendChild(tr);
    });
    document.getElementById('pool-block-rows').replaceChildren(rows);
    if (!o.recent_blocks.length) empty('No pool blocks recorded yet.');
    put('pool-stats-updated', 'Statistics updated ' + new Date().toLocaleTimeString());
  }
  var busy = false, next = 0;
  async function refresh() {
    if (busy || document.hidden || Date.now() < next) return;
    busy = true; next = Date.now() + 30000;
    var abort = new AbortController(), timer = setTimeout(function () { abort.abort(); }, 8000);
    try {
      var response = await fetch('https://pool.veld.network/v1/public', {credentials: 'omit', referrerPolicy: 'no-referrer', redirect: 'error', cache: 'no-store', signal: abort.signal});
      if (!response.ok || !response.body) throw Error('Unavailable');
      var reader = response.body.getReader(), chunks = [], size = 0;
      for (;;) { var part = await reader.read(); if (part.done) break; size += part.value.length; if (size > 32768) { await reader.cancel(); throw Error('Response too large'); } chunks.push(part.value); }
      var bytes = new Uint8Array(size), offset = 0; chunks.forEach(function (c) { bytes.set(c, offset); offset += c.length; });
      render(validate(JSON.parse(new TextDecoder('utf-8', {fatal: true}).decode(bytes))));
    } catch (_) {
      ['pool-rate', 'pool-blocks', 'pool-earned', 'pool-paid', 'pool-lottery-earned', 'pool-stake-earned'].forEach(function (id) { put(id, '—'); });
      put('pool-rate-note', 'Waiting for verified work statistics'); put('pool-paid-note', 'Confirmed payments · VELD');
      put('pool-stats-updated', 'Statistics unavailable. Retrying automatically.'); empty('Block history is temporarily unavailable.');
    } finally { clearTimeout(timer); busy = false; }
  }
  empty('Loading recent blocks…'); setInterval(refresh, 1000); refresh();
})();
)VLDPOOLUI";
inline constexpr const char* VELD_POOL_OVERVIEW_CSS =
    R"VLDPOOLUI(.pool-page{max-width:1120px;margin:0 auto;padding:12px 0 24px}
.pool-overview-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.pool-overview-grid small{color:var(--fg2,var(--muted));font:12px/1.6 var(--sans,system-ui)}#pool-overview{margin:24px 0 28px}#pool-overview .v{font-size:clamp(23px,3.5vw,34px)}.pool-block-table{overflow:auto;margin-top:16px;border:1px solid var(--line,var(--border,#343b36));border-radius:12px}.pool-block-table table{width:100%;border-collapse:collapse;font-size:14px}.pool-block-table th,.pool-block-table td{padding:16px;text-align:left;border-bottom:1px solid var(--line,var(--border,#343b36))}.pool-block-table th{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--fg2,var(--muted))}.pool-block-table tr:last-child td{border:0}.pool-block-table a{font-weight:700;text-decoration:none}.pool-block-state.pending{color:var(--gold,#d8b35b)}.pool-block-state.orphaned{color:var(--red,#ef8b85)}.pool-extra-rewards{display:flex;flex-wrap:wrap;gap:16px 32px;color:var(--fg2,var(--muted));font-size:14px}.pool-extra-rewards strong{display:block;color:var(--fg,var(--text));margin-top:4px}.pool-recent{margin:28px 0 36px}
@media(max-width:900px){.pool-overview-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:540px){.pool-block-table thead{display:none}.pool-block-table tr{display:grid;grid-template-columns:1fr 1fr;padding:8px 10px;border-bottom:1px solid var(--line,var(--border,#343b36))}.pool-block-table tr:last-child{border:0}.pool-block-table td{display:flex;flex-direction:column;gap:6px;padding:10px 6px;border:0;overflow-wrap:anywhere}.pool-block-table td::before{content:attr(data-label);font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:var(--fg2,var(--muted))}.pool-block-table td[colspan]{grid-column:1/-1}.pool-overview-grid{gap:12px}}
.pool-page h2{margin:0 0 8px}.pool-intro{margin:0 0 22px;color:var(--fg2,var(--muted));line-height:1.6}
.pool-status{padding:18px 20px;margin:0 0 16px;border:1px solid var(--line,var(--border,#343b36));border-radius:12px;background:var(--surf,var(--panel,#111713))}
.pool-status strong{font-size:14px;font-weight:600}.pool-status p{margin:6px 0 0;color:var(--fg2,var(--muted))}
.pool-page .grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-bottom:32px}.pool-page .tile{min-width:0;padding:20px;display:flex;flex-direction:column;gap:12px;border:1px solid var(--line,var(--border,#343b36));border-radius:12px;background:var(--surf,var(--panel,#111713))}
.pool-page .tile .l{font-size:11px;letter-spacing:1px;text-transform:uppercase;line-height:1.5;margin:0;color:var(--fg2,var(--muted))}.pool-page .tile .v{font-size:clamp(24px,5.8vw,36px);font-weight:700;line-height:1.2;overflow-wrap:anywhere}
.pool-page .tile .pool-word{font-family:var(--sans,system-ui,sans-serif);font-size:clamp(18px,4.4vw,24px)!important;overflow-wrap:normal;word-break:normal}
.pool-page h3{margin:28px 0 14px}.pool-page .card,.pool-page .section{padding:22px;border:1px solid var(--line,var(--border,#343b36));background:var(--surf,var(--panel,#111713));border-radius:12px;line-height:1.65}
.pool-page ol{margin:0;padding-left:1.4em}.pool-page li{padding-left:4px;margin:0 0 10px}.pool-page li:last-child{margin-bottom:0}
.pool-page p{line-height:1.65}.pool-page .pool-note{color:var(--fg2,var(--muted));font-size:14px;margin:16px 0 0}
.pool-page code{overflow-wrap:anywhere;font-size:.9em}.pool-page .btn,.pool-page .button{display:inline-flex;align-items:center;justify-content:center;min-height:46px;margin-top:8px;padding:10px 18px;border:1px solid #5b6166;border-radius:10px;background:#34383c;color:#f3f4f5;text-decoration:none;font-weight:600}
.pool-page .btn:hover,.pool-page .button:hover{background:#41464b}.pool-page .btn:focus-visible,.pool-page .button:focus-visible{outline:2px solid currentColor;outline-offset:3px}
@media(max-width:480px){.pool-page .tile{padding:16px}.pool-status{padding:16px}.pool-page .card,.pool-page .section{padding:18px}.pool-page .grid2{gap:12px}}
)VLDPOOLUI";
