#!/usr/bin/env bash
# btcveld-e2e-scene.sh — full peg-money E2E BTC legs on a real bitcoind regtest:
# a DEPOSIT tx (funds custody + commits a Veld recipient) and a PAYOUT tx (custody
# pays the redeemer's BTC address the exact owed amount), both LEGACY-serialized so
# txid == Hash256d(tx), both SPV-provable. Emits a C++ vectors header the peg-money
# E2E harness (repro_btcveld_e2e.cpp) drives the real consensus engines with.
set -euo pipefail
OUT="${1:?usage: btcveld-e2e-scene.sh <out.h>}"
DATADIR="${BTC_REGTEST_DATADIR:-/tmp/rt-btc}"
B="bitcoin-cli -datadir=$DATADIR"; W="$B -rpcwallet=custody"
JQ(){ python3 -c "import sys,json;d=json.load(sys.stdin);print($1)"; }
log(){ echo "[e2e-scene] $*" >&2; }

$B -rpcwait getblockchaininfo >/dev/null
MINE=$($W getnewaddress mine legacy)
$W generatetoaddress 110 "$MINE" >/dev/null

# identities
CUSTODY=$($W getnewaddress custody legacy)                          # P2PKH so spends are legacy
CUSTODY_SPK=$($W getaddressinfo "$CUSTODY" | JQ 'd["scriptPubKey"]')
VELD_USER="VUjD1JoewGkiGxRqJ52FkK1UiMotjsp9Tg"                      # the Veld mint recipient
USER_BTC=$($W getnewaddress redeemer legacy)                        # redeem dest + payout target (P2PKH)
USER_SPK=$($W getaddressinfo "$USER_BTC" | JQ 'd["scriptPubKey"]')
DATA_HEX=$(printf '%s' "btcVELD:${VELD_USER}" | xxd -p | tr -d '\n')
AMOUNT_BTC=0.50000000; AMOUNT_SATS=50000000
log "custody=$CUSTODY spk=$CUSTODY_SPK ; redeemer=$USER_BTC spk=$USER_SPK"

# ── DEPOSIT: legacy input -> custody 0.5 + OP_RETURN(btcVELD:user) + change ──
LEG=$($W getnewaddress leg legacy); $W sendtoaddress "$LEG" 2.0 >/dev/null; $W generatetoaddress 1 "$MINE" >/dev/null
read -r IN_TXID IN_VOUT < <($W listunspent 1 9999 "[\"$LEG\"]" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d[0]['txid'],d[0]['vout'])")
CH1=$($W getnewaddress ch1 legacy)
DRAW=$($B createrawtransaction "[{\"txid\":\"$IN_TXID\",\"vout\":$IN_VOUT}]" \
        "[{\"$CUSTODY\":$AMOUNT_BTC},{\"data\":\"$DATA_HEX\"},{\"$CH1\":1.4999}]")
DSIGNED=$($W signrawtransactionwithwallet "$DRAW" | JQ 'd["hex"]')
DEP_TXID=$($B sendrawtransaction "$DSIGNED")
DEP_BLK=$($W generatetoaddress 1 "$MINE" | JQ 'd[0]')
log "deposit txid=$DEP_TXID  (custody vout=0)"

# ── PAYOUT: custody UTXO (deposit vout 0) + a fee input -> redeemer EXACT 0.5 + change ──
FEE=$($W getnewaddress fee legacy); $W sendtoaddress "$FEE" 0.01 >/dev/null; $W generatetoaddress 1 "$MINE" >/dev/null
read -r FEE_TXID FEE_VOUT < <($W listunspent 1 9999 "[\"$FEE\"]" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d[0]['txid'],d[0]['vout'])")
CH2=$($W getnewaddress ch2 legacy)
PRAW=$($B createrawtransaction \
        "[{\"txid\":\"$DEP_TXID\",\"vout\":0},{\"txid\":\"$FEE_TXID\",\"vout\":$FEE_VOUT}]" \
        "[{\"$USER_BTC\":$AMOUNT_BTC},{\"$CH2\":0.0099}]")
PSIGNED=$($W signrawtransactionwithwallet "$PRAW" | JQ 'd["hex"]')
PAY_TXID=$($B sendrawtransaction "$PSIGNED")
PAY_BLK=$($W generatetoaddress 1 "$MINE" | JQ 'd[0]')
log "payout txid=$PAY_TXID -> redeemer 0.5 BTC"

# bury both K deep
K=3; $W generatetoaddress "$K" "$MINE" >/dev/null
DEP_H=$($B getblock "$DEP_BLK" 1 | JQ 'd["height"]'); PAY_H=$($B getblock "$PAY_BLK" 1 | JQ 'd["height"]')
TIP=$($B getblockcount)
CP_H=$((DEP_H - 5)); CP_HASH=$($B getblockhash $CP_H)
log "deposit@$DEP_H payout@$PAY_H tip=$TIP checkpoint@$CP_H"

# legacy tx hex (sanity: not segwit)
DEP_HEX=$($B getrawtransaction "$DEP_TXID" false); [ "${DEP_HEX:8:4}" = "0001" ] && { log FATAL deposit segwit; exit 1; }
PAY_HEX=$($B getrawtransaction "$PAY_TXID" false); [ "${PAY_HEX:8:4}" = "0001" ] && { log FATAL payout segwit; exit 1; }

emit_txids(){ $B getblock "$1" 1 | python3 -c "import sys,json;[print('  \"%s\",'%t) for t in json.load(sys.stdin)['tx']]"; }
didx(){ $B getblock "$1" 1 | python3 -c "import sys,json;print(json.load(sys.stdin)['tx'].index('$2'))"; }
ntx(){ $B getblock "$1" 1 | python3 -c "import sys,json;print(len(json.load(sys.stdin)['tx']))"; }

{
echo "#pragma once"
echo "// AUTO-GENERATED by scripts/btcveld-e2e-scene.sh — real bitcoind regtest peg-money E2E."
echo "#include <cstdint>"
echo "namespace e2e {"
echo "static const char* CP_HASH_BE=\"$CP_HASH\"; static const unsigned CP_HEIGHT=$CP_H;"
echo "static const char* CP_HEADER_HEX=\"$($B getblockheader "$CP_HASH" false)\";"
printf 'static const unsigned CP_PREV10_TIMES[10]={'; for h in $(seq $((CP_H-10)) $((CP_H-1))); do bh=$($B getblockhash "$h"); printf '%s,' "$($B getblockheader "$bh" true | JQ 'd["time"]')"; done; echo '};'
echo "static const char* HEADERS_HEX[]={"
for h in $(seq $((CP_H+1)) "$TIP"); do bh=$($B getblockhash "$h"); echo "  \"$($B getblockheader "$bh" false)\","; done
echo "}; static const int N_HEADERS=$((TIP-CP_H));"
echo "static const char* CUSTODY_SPK_HEX=\"$CUSTODY_SPK\"; static const char* USER_SPK_HEX=\"$USER_SPK\";"
echo "static const char* VELD_USER=\"$VELD_USER\"; static const unsigned long long AMOUNT_SATS=${AMOUNT_SATS}ULL;"
echo "// deposit leg"
echo "static const char* DEP_BLK_BE=\"$DEP_BLK\"; static const char* DEP_TX_HEX=\"$DEP_HEX\"; static const int DEP_IDX=$(didx "$DEP_BLK" "$DEP_TXID");"
echo "static const char* DEP_TXIDS_BE[]={"; emit_txids "$DEP_BLK"; echo "}; static const int DEP_NTX=$(ntx "$DEP_BLK");"
echo "// payout leg"
echo "static const char* PAY_BLK_BE=\"$PAY_BLK\"; static const char* PAY_TX_HEX=\"$PAY_HEX\"; static const int PAY_IDX=$(didx "$PAY_BLK" "$PAY_TXID");"
echo "static const char* PAY_TXIDS_BE[]={"; emit_txids "$PAY_BLK"; echo "}; static const int PAY_NTX=$(ntx "$PAY_BLK");"
echo "static const int K_BTC=$K;"
echo "}"
} > "$OUT"
log "wrote $OUT ($(wc -l <"$OUT") lines)"
