#!/usr/bin/env python3
"""Prepare, without installing, Explorer page-error nginx configuration.

The generated snippet belongs in the Explorer server block; API handling,
rate budgets, caches and the wallet server remain unchanged. Review and test
both outputs before installation. This script does not reload any service.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNIPPET_PATH = '/etc/nginx/snippets/veld-explorer-page-errors.conf'


def error_snippet(html):
    # nginx evaluates variables even in quoted strings. No request data or
    # variable interpolation belongs in this fixed, self-contained page.
    if '$' in html or '\\' in html or "'" in html:
        raise ValueError('Error-page HTML must not contain nginx interpolation or escapes')
    parts = ['# Generated by scripts/configure-explorer-error-pages.py.\n']
    for name, status, retry in [('throttled', 429, 60), ('busy', 503, 2)]:
        parts.append(f'''location @explorer_page_{name} {{
    internal;
    default_type text/html;
    charset utf-8;
    add_header Cache-Control "no-store" always;
    add_header Retry-After "{retry}" always;
    include /etc/nginx/snippets/veld-security-headers.conf;
    add_header Content-Security-Policy "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'" always;
    return {status} '{html}';
}}
''')
    return '\n'.join(parts)


def configure_site(site):
    if SNIPPET_PATH in site:
        raise ValueError('Explorer page-error configuration is already installed')
    start = site.index('    server_name explorer.veld.network;')
    end = site.index('\nserver {', start)
    explorer = site[start:end]
    marker = '    include /etc/nginx/snippets/veld-security-headers.conf;'
    explorer = explorer.replace(marker, marker + '\n    include ' + SNIPPET_PATH + ';', 1)
    for selector in ['    location = /blocks {', '    location / {']:
        begin = explorer.index(selector)
        finish = explorer.index('\n    }', begin)
        location = explorer[begin:finish]
        old = '        proxy_intercept_errors off;'
        if location.count(old) != 1:
            raise ValueError('Unexpected intercept configuration in ' + selector)
        location = location.replace(old, '''        proxy_intercept_errors on;
        error_page 429 = @explorer_page_throttled;
        error_page 502 503 504 = @explorer_page_busy;''')
        explorer = explorer[:begin] + location + explorer[finish:]
    return site[:start] + explorer + site[end:]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--site', type=Path, required=True)
    parser.add_argument('--site-output', type=Path, required=True)
    parser.add_argument('--snippet-output', type=Path, required=True)
    args = parser.parse_args()
    if len({p.resolve() for p in (args.site, args.site_output, args.snippet_output)}) != 3:
        parser.error('Input and output paths must be distinct')
    candidate = configure_site(args.site.read_text(encoding='utf8'))
    snippet = error_snippet((ROOT / 'website/explorer-busy.html').read_text(encoding='utf8'))
    args.site_output.write_text(candidate, encoding='utf8', newline='\n')
    args.snippet_output.write_text(snippet, encoding='utf8', newline='\n')
