#!/usr/bin/env python3
"""Regenerate Veld's public ML-DSA-65 startup KAT from exact PQClean bytes."""

from __future__ import annotations

import argparse
from io import BytesIO
import hashlib
import os
from pathlib import Path, PurePosixPath
import shutil
import subprocess
import sys
import tarfile
import tempfile


PQCLEAN_REVISION = "202a8f96315f9ed219387a50f7e40d04af037ea8"
PQCLEAN_META_PATH = "crypto_sign/ml-dsa-65/META.yml"
PQCLEAN_META_SHA256 = (
    "e83150131384d5e43a2a59baedcef96c48f5bbf4dce9377094f9bdc3ed12f7d6"
)
PQCLEAN_KAT_SHA256 = (
    "7cb96242eac9907a55b5c84c202f0ebd552419c50b2e986dc2e28f07ecebf072"
)
HEADER_REL = PurePosixPath("include/crypto/mldsa65_nist_kat.h")

KAT_SOURCES = (
    "test/crypto_sign/nistkat.c",
    "common/aes.c",
    "common/sha2.c",
    "common/fips202.c",
    "common/nistseedexpander.c",
    "common/sp800-185.c",
    "test/common/nistkatrng.c",
    "crypto_sign/ml-dsa-65/clean/ntt.c",
    "crypto_sign/ml-dsa-65/clean/packing.c",
    "crypto_sign/ml-dsa-65/clean/poly.c",
    "crypto_sign/ml-dsa-65/clean/polyvec.c",
    "crypto_sign/ml-dsa-65/clean/reduce.c",
    "crypto_sign/ml-dsa-65/clean/rounding.c",
    "crypto_sign/ml-dsa-65/clean/sign.c",
    "crypto_sign/ml-dsa-65/clean/symmetric-shake.c",
)


class KatError(RuntimeError):
    pass


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git(upstream: Path, *args: str) -> bytes:
    proc = subprocess.run(
        ["git", "-C", str(upstream), *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise KatError(
            "git " + " ".join(args) + " failed: "
            + proc.stderr.decode("utf-8", "replace").strip()
        )
    return proc.stdout


def extract_exact_tree(upstream: Path, destination: Path) -> None:
    archive = git(upstream, "archive", "--format=tar", PQCLEAN_REVISION)
    with tarfile.open(fileobj=BytesIO(archive), mode="r:") as tf:
        for member in tf.getmembers():
            rel = PurePosixPath(member.name)
            if rel.is_absolute() or ".." in rel.parts:
                raise KatError(f"unsafe path in PQClean archive: {member.name!r}")
            if not (member.isdir() or member.isfile()):
                raise KatError(f"non-regular path in PQClean archive: {member.name!r}")
        tf.extractall(destination)


def quote_hex(value: str) -> str:
    chunks = [value[i:i + 96] for i in range(0, len(value), 96)]
    return "\n".join(
        f'    "{chunk}"' + (";" if i == len(chunks) - 1 else "")
        for i, chunk in enumerate(chunks)
    )


def build_header(message: str, public_key: str, signature: str) -> bytes:
    return (
        "#pragma once\n"
        "\n"
        "#include <cstddef>\n"
        "\n"
        "// AUTO-GENERATED by scripts/generate-mldsa65-nist-kat.py from the\n"
        f"// first ML-DSA-65 NIST KAT at PQClean {PQCLEAN_REVISION}.\n"
        f"// The complete canonical response SHA-256 is {PQCLEAN_KAT_SHA256}.\n"
        "// Only the public message, public key, and detached signature are retained.\n"
        "namespace veld {\n"
        "namespace crypto {\n"
        "namespace mldsa65_kat {\n"
        "\n"
        "inline constexpr char kMessageHex[] =\n"
        f"{quote_hex(message)}\n"
        "inline constexpr char kPublicKeyHex[] =\n"
        f"{quote_hex(public_key)}\n"
        "inline constexpr char kSignatureHex[] =\n"
        f"{quote_hex(signature)}\n"
        "\n"
        "static_assert(sizeof(kMessageHex) - 1 == 33 * 2, "
        "\"ML-DSA-65 KAT message length\");\n"
        "static_assert(sizeof(kPublicKeyHex) - 1 == 1952 * 2, "
        "\"ML-DSA-65 KAT public key length\");\n"
        "static_assert(sizeof(kSignatureHex) - 1 == 3309 * 2, "
        "\"ML-DSA-65 KAT signature length\");\n"
        "\n"
        "}  // namespace mldsa65_kat\n"
        "}  // namespace crypto\n"
        "}  // namespace veld\n"
    ).encode("ascii")


def generate(upstream: Path, compiler: str) -> bytes:
    head = git(upstream, "rev-parse", "HEAD").decode("ascii").strip()
    if head != PQCLEAN_REVISION:
        raise KatError(f"PQClean checkout must be exact commit {PQCLEAN_REVISION}")
    meta = git(upstream, "show", f"{PQCLEAN_REVISION}:{PQCLEAN_META_PATH}")
    if sha256(meta) != PQCLEAN_META_SHA256:
        raise KatError("PQClean ML-DSA-65 META.yml raw hash mismatch")
    marker = f"nistkat-sha256: {PQCLEAN_KAT_SHA256}".encode("ascii")
    if marker not in meta:
        raise KatError("PQClean metadata does not bind the canonical KAT hash")

    with tempfile.TemporaryDirectory(prefix="veld-pqclean-kat-") as td:
        exact = Path(td) / "PQClean"
        exact.mkdir()
        extract_exact_tree(upstream, exact)
        executable = Path(td) / ("nistkat.exe" if os.name == "nt" else "nistkat")
        scheme = exact / "crypto_sign/ml-dsa-65/clean"
        common = exact / "common"
        command = [
            compiler,
            "-std=c99",
            "-O3",
            "-DPQCLEAN_NAMESPACE=PQCLEAN_MLDSA65_CLEAN",
            f"-I{common}",
            f"-I{scheme}",
            *(str(exact / Path(*PurePosixPath(rel).parts)) for rel in KAT_SOURCES),
            "-o",
            str(executable),
        ]
        built = subprocess.run(
            command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False
        )
        if built.returncode != 0:
            raise KatError(
                "PQClean NIST KAT compile failed: "
                + built.stderr.decode("utf-8", "replace").strip()
            )
        ran = subprocess.run(
            [str(executable)], stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            check=False,
        )
        if ran.returncode != 0:
            raise KatError(
                "PQClean NIST KAT execution failed: "
                + ran.stderr.decode("utf-8", "replace").strip()
            )

    response = ran.stdout.replace(b"\r\n", b"\n")
    if b"\r" in response or sha256(response) != PQCLEAN_KAT_SHA256:
        raise KatError("generated PQClean NIST response hash mismatch")
    fields: dict[str, str] = {}
    for raw_line in response.decode("ascii").splitlines():
        parts = raw_line.split(" = ", 1)
        if len(parts) != 2 or parts[0] in fields:
            raise KatError("malformed or duplicate field in PQClean KAT output")
        fields[parts[0]] = parts[1]
    if set(fields) != {"count", "seed", "mlen", "msg", "pk", "sk", "smlen", "sm"}:
        raise KatError("unexpected PQClean KAT output schema")
    if fields["count"] != "0" or fields["mlen"] != "33" or fields["smlen"] != "3342":
        raise KatError("unexpected PQClean KAT dimensions")
    message = fields["msg"]
    signed_message = fields["sm"]
    if len(message) != 33 * 2 or not signed_message.endswith(message):
        raise KatError("PQClean signed-message encoding is inconsistent")
    signature = signed_message[:-len(message)]
    if len(fields["pk"]) != 1952 * 2 or len(signature) != 3309 * 2:
        raise KatError("PQClean public KAT field length mismatch")
    # The deterministic seed and secret key are intentionally discarded here.
    return build_header(message, fields["pk"], signature)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream-dir", type=Path, required=True)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parents[1]
    )
    parser.add_argument("--cc", default=os.environ.get("CC"))
    parser.add_argument("--write-header", action="store_true")
    args = parser.parse_args()
    compiler = args.cc or shutil.which("clang") or shutil.which("gcc")
    if not compiler:
        raise KatError("a C99 compiler is required for PQClean KAT regeneration")
    expected = generate(args.upstream_dir.resolve(), compiler)
    header = args.root.resolve() / Path(*HEADER_REL.parts)
    if args.write_header:
        header.write_bytes(expected)
    if not header.is_file() or header.read_bytes() != expected:
        raise KatError(f"{HEADER_REL} differs from exact PQClean KAT generation")
    print(
        "PASS ML-DSA-65 NIST KAT source proof "
        f"pqclean={PQCLEAN_REVISION} response_sha256={PQCLEAN_KAT_SHA256}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (KatError, OSError, UnicodeError) as exc:
        print(f"FAIL ML-DSA-65 NIST KAT source proof: {exc}", file=sys.stderr)
        raise SystemExit(1)
