"""Embed the same public-only overview used by hosted Explorer origins."""

from pathlib import Path

root = Path(__file__).resolve().parents[1]
js = (root / 'website/explorer-pool-overview-v2.js').read_text(encoding='utf-8')
css = (root / 'website/explorer-pool-ui-v1.css').read_text(encoding='utf-8')
compat = root / 'website/explorer-pool-ui-v1.js'
marker = '/* BEGIN GENERATED PUBLIC POOL OVERVIEW */'
nav = compat.read_text(encoding='utf-8').split(marker)[0].rstrip()
compat.write_text(nav + '\n\n' + marker + '\n' + js, encoding='utf-8', newline='\n')
assert ')VLDPOOLUI"' not in js + css
header = (
    '// Generated by scripts/generate-pool-overview-ui.py.\n#pragma once\n'
    'inline constexpr const char* VELD_POOL_OVERVIEW_JS = R"VLDPOOLUI(' + js + ')VLDPOOLUI";\n'
    'inline constexpr const char* VELD_POOL_OVERVIEW_CSS = R"VLDPOOLUI(' + css + ')VLDPOOLUI";\n'
)
(root / 'include/network/ui_pool_overview.h').write_text(header, encoding='utf-8', newline='\n')
